defaults :
  - physicsnemo_default
  - arch:
      - fully_connected
  - optimizer : adam
  - scheduler : tf_exponential_lr
  - loss : sum  
  - _self_

jit: false

optimizer:
  lr: 1e-3
  
arch:
  fully_connected:
    layer_size: 20
    nr_layers: 5


scheduler:
  decay_rate: 0.95
  decay_steps: 1000

training:
  rec_results_freq: 100
  rec_inference_freq: 10
  rec_monitor_freq: 5000
  rec_constraint_freq: 10
  max_steps : 10000

batch_size:
  BC: 1024
  IC: 1024
  interior: 20000
  inference: 1024